# -- Main Menu --

[[main]]
  name = "Laboratorio de inovaci√≥n"
  pageRef = "laboratorio"
  weight = 10
  pre = "beaker"

[[main]]
  name = "Recursos y herramientas"
  pageRef = "recursos"
  weight = 20
  pre = "cpu-chip"

[[main]]
  name = "Cultura Digital"
  pageRef = "cultura-digital"
  weight = 30
  pre = "scale"

[[main]]
  name = "Normas y orientaciones"
  pageRef = "acuerdos"
  weight = 40
  pre = "document-text"
